### ISSUE TITLE
Doesn't work with *.ft.com

### ISSUE THREAD

**Issue by radiolondra** [arkadiyt/free-ft#1]
Sites like [markets.ft.com](https://markets.ft.com/data) continue to show the GDPR even if they have the same cookie to set (`FTCookieConsentGDPR`).
Any idea?

**Comment by arkadiyt** [comment]
Here's an example of what I see on markets.ft.com - I'm not seeing any notice?

![markets ft com_data](https://user-images.githubusercontent.com/2279289/205477123-13d78a96-952f-4781-93fe-c39bf32602c4.png)

**Comment by arkadiyt** [comment]
Nevermind, I browse ft with javascript disabled - when I enabled javascript I was able to reproduce the issue. Fixed with https://github.com/arkadiyt/free-ft/commit/97928184e60a57cce9238f8e631d4ad64c5be10f - thanks for flagging
