### ISSUE TITLE
Free Access to FT and other newspapers

### ISSUE THREAD

**Issue by santa-maura** [arkadiyt/free-ft#3]
I am struggling to get the access, it doesn't work anymore. On the extension there is a message of error: "Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details."
So I don't believe Bypass Paywalls 1.8.1 is working anymore I am afraid.
Thank you. 
![Capture](https://github.com/arkadiyt/free-ft/assets/173382321/fb5e4856-b630-4f40-be4e-93f60af0969a)

**Comment by arkadiyt** [comment]
This isn't Bypass-Paywalls, it's Free-FT

**Comment by santa-maura** [comment]
Hello, thanks for your reply, but it's cryptic to me, my apologies. What should I do to make it work ? Thanks

**Comment by arkadiyt** [comment]
> What should I do to make it work ? Thanks

I would file a github issue with the author of Bypass-Paywalls. I am the author of Free-FT

**Comment by santa-maura** [comment]
I understand now. And in the meantime, I have followed your instructions. It has to be said I have absolutely no understanding of any of this, I just a mere reader of the FT, but I can make it work, so thank you very much.
